from typing import no_type_check, Any


@no_type_check
class Expando:
    def __init__(self, **attrib): ...
    def __setattr__(self, key: str, value: Any) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
