from typing import no_type_check, Dict, Any


@no_type_check
class Expando:
    def __init__(self, **attrib): ...
    def _replace(self, **attrib) -> Expando: ...
    def _asdict(self) -> Dict[str, Any]: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
